import React from 'react';
import Head from 'next/head';

import { Navbar, Footer } from '../../components';
import Script from "next/script";

const Layout = ({ children }) => {
    return (
        <div className={"layout"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta charSet="utf-8" />
                <Script src="/assets/js/vendor.min.js"></Script>
                <Script src="/assets/js/app.js"></Script>
            </Head>
            <Navbar />

            <main className={"main-container"} style={{ paddingTop: '80px' }}> {/* Adjust the value based on the height of your navbar */}
                {children}
            </main>
            <footer>
                <Footer />
            </footer>
        </div>
    );
};

export default Layout;
